@startuml

actor HR as "HR Advisor"

rectangle Database

rectangle "HR System" {
    usecase UC4 as "Get population
    by countries"

    usecase UCa as "Print information"

    HR - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml
