name: A workflow for my Hello World App
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Maven
        uses: actions/setup-maven@v3
        with:
          maven-version: '3.8.6'

      - name: Compile with Maven
        run: mvn compile

      - name: Verify Docker Installation
        run: docker --version

      - name: Clean up existing container
        run: |
          if [ "$(docker ps -aq -f name=semcontainer)" ]; then
            docker rm -f semcontainer
          fi

      - name: Clean up existing image
        run: |
          if [ "$(docker images -q semimage)" ]; then
            docker rmi -f semimage
          fi

      - name: Build Docker Image
        run: docker build -t semimage .

      - name: Run image
        run: docker run --name semcontainer -d semimage

      - name: View logs
        run: docker logs semcontainer
